version: '3'
services:
    firefox:
        # Build the dockerfile
        build: .
        # Mouting /dev/shm is a workaround for browser crashes inside docker. See https://github.com/SeleniumHQ/docker-selenium#quick-start
        volumes:
            - /dev/shm:/dev/shm
        # Give the container a fixed name, because we may need to restart it from python
        container_name: firefox
        # Use our host machine's connection so we get IPv6
        network_mode: 'host'
